services:
  # 1. Container Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: okoce_user
      POSTGRES_PASSWORD: okoce_password
      POSTGRES_DB: okoce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 2. Container Aplikasi (Flask)
  web:
    build: .
    restart: always
    ports:
      - "8002:8000"
    
    env_file:
      - .env
    
    environment:
      - DATABASE_URL=postgresql://okoce_user:okoce_password@172.17.0.1:5432/okoce_db

    volumes:
      - ./uploads:/app/uploads
      - ./firebase-service-account-key.json:/app/firebase-service-account-key.json

